Repository ICube-Robotics/cartesian_controllers_ros2, pull requests merged in 2024-08, with the labels that each got.

#23 make CI happy
  .github/mergify.yml
  README.md
  cartesian_vic_controller/README.md
Labels: documentation, backport-humble

#8 added cartesian velocity controller
  cartesian_velocity_controller/CHANGELOG.rst
  cartesian_velocity_controller/CMakeLists.txt
  cartesian_velocity_controller/controller_plugin.xml
  cartesian_velocity_controller/include/cartesian_velocity_controller/cartesian_velocity_controller.hpp
  cartesian_velocity_controller/include/cartesian_velocity_controller/visibility_control.h
  cartesian_velocity_controller/package.xml
  cartesian_velocity_controller/src/cartesian_velocity_controller.cpp
  cartesian_velocity_controller/src/cartesian_velocity_controller_parameters.yaml
  cartesian_velocity_controller/test/test_load_cartesian_velocity_controller.cpp
Labels: enhancement, backport-humble

#30 Major fixes before experimentation
  cartesian_control_msgs/msg/VicControllerState.msg
  cartesian_vic_controller/CMakeLists.txt
  cartesian_vic_controller/cartesian_vic_rules.xml
  cartesian_vic_controller/include/cartesian_vic_controller/cartesian_vic_rule.hpp
  cartesian_vic_controller/include/cartesian_vic_controller/cartesian_vic_state.hpp
  cartesian_vic_controller/include/cartesian_vic_controller/rules/fd_impedance_rule.hpp
  cartesian_vic_controller/include/cartesian_vic_controller/rules/vanilla_cartesian_admittance_rule.hpp
  cartesian_vic_controller/include/cartesian_vic_controller/rules/vanilla_cartesian_impedance_rule.hpp
  cartesian_vic_controller/include/cartesian_vic_controller/vic_msgs_utils.hpp
  cartesian_vic_controller/src/cartesian_vic_controller.cpp
  cartesian_vic_controller/src/cartesian_vic_controller_parameters.yaml
  cartesian_vic_controller/src/cartesian_vic_rule.cpp
  cartesian_vic_controller/src/cartesian_vic_state.cpp
  cartesian_vic_controller/src/rules/fd_impedance_rule.cpp
  cartesian_vic_controller/src/rules/vanilla_cartesian_admittance_rule.cpp
  cartesian_vic_controller/src/rules/vanilla_cartesian_impedance_rule.cpp
  cartesian_vic_controller/src/utils.cpp
Labels: enhancement, backport-humble

#32 fix adm control
  cartesian_vic_controller/config/example_admittance_controller_config.yaml
  cartesian_vic_controller/config/example_impedance_controller_config.yaml
  cartesian_vic_controller/include/cartesian_vic_controller/cartesian_vic_rule.hpp
  cartesian_vic_controller/include/cartesian_vic_controller/cartesian_vic_state.hpp
  cartesian_vic_controller/include/cartesian_vic_controller/rules/vanilla_cartesian_admittance_rule.hpp
  cartesian_vic_controller/include/cartesian_vic_controller/rules/vanilla_cartesian_impedance_rule.hpp
  cartesian_vic_controller/src/cartesian_vic_controller_parameters.yaml
  cartesian_vic_controller/src/cartesian_vic_rule.cpp
  cartesian_vic_controller/src/cartesian_vic_state.cpp
  cartesian_vic_controller/src/rules/vanilla_cartesian_admittance_rule.cpp
  cartesian_vic_controller/src/rules/vanilla_cartesian_impedance_rule.cpp
  cartesian_vic_controller/test/test_cartesian_vic_controller.hpp
Labels: bug, backport-humble

#35 add teleop controller
  cartesian_control_msgs/CMakeLists.txt
  cartesian_control_msgs/msg/TeleopCompliance.msg
  cartesian_control_msgs/msg/TeleopControllerState.msg
  cartesian_vic_controller/CMakeLists.txt
  cartesian_vic_teleop_controller/CMakeLists.txt
  cartesian_vic_teleop_controller/cartesian_vic_teleop_controller.xml
  cartesian_vic_teleop_controller/cartesian_vic_teleop_rules.xml
  cartesian_vic_teleop_controller/include/cartesian_vic_teleop_controller/Ros2VersionConfig.h.in
  cartesian_vic_teleop_controller/include/cartesian_vic_teleop_controller/cartesian_vic_teleop_controller.hpp
  cartesian_vic_teleop_controller/include/cartesian_vic_teleop_controller/cartesian_vic_teleop_logic.hpp
  cartesian_vic_teleop_controller/include/cartesian_vic_teleop_controller/mapping_manager.hpp
  cartesian_vic_teleop_controller/include/cartesian_vic_teleop_controller/rules/vanilla_teleop_rule.hpp
  cartesian_vic_teleop_controller/include/cartesian_vic_teleop_controller/teleop_data.hpp
  cartesian_vic_teleop_controller/include/cartesian_vic_teleop_controller/teleop_rule.hpp
  cartesian_vic_teleop_controller/include/cartesian_vic_teleop_controller/visibility_control.h
  cartesian_vic_teleop_controller/package.xml
  cartesian_vic_teleop_controller/src/cartesian_vic_teleop_controller.cpp
  cartesian_vic_teleop_controller/src/cartesian_vic_teleop_logic.cpp
  cartesian_vic_teleop_controller/src/mapping_manager.cpp
  cartesian_vic_teleop_controller/src/rules/vanilla_teleop_rule.cpp
  cartesian_vic_teleop_controller/src/teleop_data.cpp
  cartesian_vic_teleop_controller/src/teleop_rule.cpp
Labels: enhancement, backport-humble
